name: ChromaDMX
options:
  bundleIdPrefix: com.chromadmx
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.10"
    DEVELOPMENT_TEAM: "3HZPZ5X2U3"
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: "x86_64"

targets:
  ChromaDMX:
    type: application
    platform: iOS
    sources:
      - path: ChromaDMX
        excludes:
          - "**/.DS_Store"
    info:
      path: ChromaDMX/Info.plist
      properties:
        CFBundleName: ChromaDMX
        CFBundleDisplayName: ChromaDMX
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        CADisableMinimumFrameDurationOnPhone: true
        NSCameraUsageDescription: "ChromaDMX uses the camera to detect and map fixture positions in your venue."
        NSLocalNetworkUsageDescription: "ChromaDMX communicates with DMX lighting nodes on your local network."
        NSBonjourServices:
          - _artnet._udp
          - _sacn._udp
        NSBluetoothAlwaysUsageDescription: "ChromaDMX uses Bluetooth to discover and configure ESP32 DMX nodes."
    entitlements:
      path: ChromaDMX/ChromaDMX.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chromadmx.app
        INFOPLIST_FILE: ChromaDMX/Info.plist
        CODE_SIGN_ENTITLEMENTS: ChromaDMX/ChromaDMX.entitlements
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
        FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]:
          - "$(inherited)"
          - "$(SRCROOT)/../shared/build/bin/iosSimulatorArm64/debugFramework"
        FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]:
          - "$(inherited)"
          - "$(SRCROOT)/../shared/build/bin/iosArm64/debugFramework"
          - "$(SRCROOT)/../shared/build/bin/iosArm64/releaseFramework"
        OTHER_LINKER_FLAGS:
          - "$(inherited)"
          - "-framework"
          - "Shared"
          - "-lsqlite3"
      configs:
        Release:
          FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]:
            - "$(inherited)"
            - "$(SRCROOT)/../shared/build/bin/iosArm64/releaseFramework"
    dependencies:
      - sdk: Network.framework
      - sdk: AVFoundation.framework
      - sdk: CoreMedia.framework
      - sdk: CoreVideo.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: CoreBluetooth.framework
      - sdk: libsqlite3.tbd
    preBuildScripts:
      - name: "Build KMP Shared Framework"
        script: |
          cd "$SRCROOT/.."
          if [ "$PLATFORM_NAME" = "iphonesimulator" ]; then
            ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64
          else
            if [ "$CONFIGURATION" = "Release" ]; then
              ./gradlew :shared:linkReleaseFrameworkIosArm64
            else
              ./gradlew :shared:linkDebugFrameworkIosArm64
            fi
          fi
        basedOnDependencyAnalysis: false
